refactor: generate nomad scripts from templates (#34)

diff --git a/infrastructure/ansible/playbooks/nomad/templates/nomad/mev-commit-funder.nomad.j2 b/infrastructure/ansible/playbooks/nomad/templates/nomad/mev-commit-funder.nomad.j2
--- a/infrastructure/ansible/playbooks/nomad/templates/nomad/mev-commit-funder.nomad.j2
+++ b/infrastructure/ansible/playbooks/nomad/templates/nomad/mev-commit-funder.nomad.j2
@@ -1,11 +1,12 @@
-job "mev-commit-provider-node1-funder" {
-  datacenters = ["dc1"]
+#jinja2: trim_blocks:True, lstrip_blocks:True
+job "{{ job.name }}" {
+  datacenters = ["{{ datacenter }}"]
   type = "batch"
 
-  group "mev-commit-provider-node-funder-group" {
-    count = 1
+  group "{{ job.name }}-group" {
+    count = {{ job.count }}
 
-    task "provider-node-funder" {
+    task "funder" {
       driver = "exec"
 
       artifact {
@@ -16,14 +17,15 @@ job "mev-commit-provider-node1-funder" {
         data = <<-EOH
           #!/usr/bin/env bash
 
-        {{- range nomadService "datadog-agent-logs-collector" }}
-          {{ if contains "tcp" .Tags }}
+          {% raw %}
+          {{- range nomadService "datadog-agent-logs-collector" }}
+            {{ if contains "tcp" .Tags }}
           exec > >(nc {{ .Address }} {{ .Port }}) 2>&1
-          {{ end }}
-        {{- end }}
+            {{ end }}
+          {{- end }}
 
-        {{- range nomadService "mev-commit-provider-node1" }}
-          {{- if contains "http" .Tags }}
+          {{- range nomadService "{% endraw %}{{ job.target_name }}{% raw %}" }}
+            {{- if contains "http" .Tags }}
           START_TIME=$(date +%s)
           TIMEOUT=60
 
@@ -36,7 +38,7 @@ job "mev-commit-provider-node1-funder" {
                   ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
 
                   if [ "${ELAPSED_TIME}" -ge "${TIMEOUT}" ]; then
-                      echo "Timeout reached; the provider node is not up."
+                      echo "Timeout reached; the node is unreachable."
                       exit 1
                   fi
                   sleep 1
@@ -46,21 +48,31 @@ job "mev-commit-provider-node1-funder" {
           TOPOLOGY=$(curl -s https://{{ .Address }}:{{ .Port }}/topology)
           ETHEREUM_ADDRESS=$(echo ${TOPOLOGY} | jq -r '.self["Ethereum Address"]')
 
-          {{- range nomadService "mev-commit-geth-bootnode1" }}
-            {{- if contains "http" .Tags }}
+            {{- range nomadService "mev-commit-geth-bootnode1" }}
+              {{- if contains "http" .Tags }}
             local/cast send \
                  --rpc-url http://{{ .Address }}:{{ .Port }} \
                  --private-key 0x7c9bf0f015874594d321c1c01ada3166c3509bbd91f76f9e4d7380c2df269c55 ${ETHEREUM_ADDRESS} \
                  --value 100ether
+              {{- end }}
             {{- end }}
-          {{- end }}
+          {% endraw %}
 
-          if ! curl -s -X POST https://{{ .Address }}:{{ .Port }}/v1/provider/register_stake/10000000000000000000 > /dev/null; then
-            echo "Failed to send provider registration transaction."
+          {% if job.target_type == 'provider' %}
+          if ! curl -s -X POST https://{% raw %}{{ .Address }}:{{ .Port }}{% endraw %}/v1/provider/register_stake/10000000000000000000 > /dev/null; then
+          {% elif job.target_type == 'bidder' %}
+          if ! curl -s -X POST https://{% raw %}{{ .Address }}:{{ .Port }}{% endraw %}/v1/bidder/prepay/1000000000000000000 > /dev/null; then
+          {% else %}
+          echo "Invalid target type: {{ job.target_type }}"
+          exit 1
+          {% endif %}
+            echo "Failed to send {{ job.target_type }} transaction."
             exit 1
           fi
+          {%- raw %}
+            {{- end }}
           {{- end }}
-        {{- end }}
+          {% endraw %}
         EOH
         destination = "local/run.sh"
         perms = "0755"
