check for beacon emulator

diff --git a/infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2 b/infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
--- a/infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
+++ b/infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
@@ -281,28 +281,43 @@ job "{{ job.name }}" {
           > local/${DEPLOY_TYPE}_addresses.json
 
           "${FORGE_BIN_PATH}" clean --root "${CONTRACT_REPO_ROOT_PATH}"
-          start_time=$(date +%s)
-          export DEPLOY_TYPE="validator-registry"
-          echo "Deploying ${DEPLOY_TYPE} contracts..."
-          LOGS="$(./entrypoint.sh)"
+          
+          # Only deploy validator-registry when beacon-emulator is running
+          {%- raw %}
+          BEACON_EMULATOR_RUNNING=false
+          {{- range nomadService "beacon-emulator" }}
+            BEACON_EMULATOR_RUNNING=true
+          {{- end }}
+          {% endraw %}
+          
+          if [ "$BEACON_EMULATOR_RUNNING" = true ]; then
+          
+            start_time=$(date +%s)
+            export DEPLOY_TYPE="validator-registry"
+            echo "Deploying ${DEPLOY_TYPE} contracts..."
+            LOGS="$(./entrypoint.sh)"
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to deploy ${DEPLOY_TYPE} contracts!"
+              echo "${LOGS}"
+              exit 1
+            fi
+            end_time=$(date +%s)
+            echo "${DEPLOY_TYPE} contracts deployed successfully in: $(date -ud @$((end_time - start_time)) +'%H:%M:%S')."
+            echo "${LOGS}" \
+            | sed -n '/{.*}/p' \
+            | jq -c 'reduce .logs[] as $item ({}; . + {($item | split(": ")[0]): ($item | split(": ")[1])})' \
+            | jq -c 'with_entries(select(.key | startswith("_") | not))' \
+            > local/${DEPLOY_TYPE}_addresses.json
+          
+          else
+            echo "Skipping validator-registry deployment as beacon-emulator is not running"
+          fi
+
+          {%- endif %}
 
           # Now cd back to previous directory.
           cd ../../
-
-          if [ $? -ne 0 ]; then
-            echo "Failed to deploy ${DEPLOY_TYPE} contracts!"
-            echo "${LOGS}"
-            exit 1
-          fi
-          end_time=$(date +%s)
-          echo "${DEPLOY_TYPE} contracts deployed successfully in: $(date -ud @$((end_time - start_time)) +'%H:%M:%S')."
-          echo "${LOGS}" \
-          | sed -n '/{.*}/p' \
-          | jq -c 'reduce .logs[] as $item ({}; . + {($item | split(": ")[0]): ($item | split(": ")[1])})' \
-          | jq -c 'with_entries(select(.key | startswith("_") | not))' \
-          > local/${DEPLOY_TYPE}_addresses.json
-
-          {%- endif %}
 
           mkdir -p /local/data/www > /dev/null 2>&1
           jq -s 'add' local/*_addresses.json > local/data/www/contracts.json
