fix: add infra components

diff --git a/infrastructure/nomad/playbooks/templates/jobs/instant-bridge.nomad.j2 b/infrastructure/nomad/playbooks/templates/jobs/instant-bridge.nomad.j2
--- a/infrastructure/nomad/playbooks/templates/jobs/instant-bridge.nomad.j2
+++ b/infrastructure/nomad/playbooks/templates/jobs/instant-bridge.nomad.j2
@@ -68,18 +68,6 @@ job "{{ job.name }}" {
 
       template {
         data = <<-EOH
-          {%- raw %}
-          {{- with secret "secret/data/mev-commit" }}
-          {{- .Data.data.instant_bridge_private_key }}
-          {{- end }}
-          {% endraw %}
-        EOH
-        destination = "secrets/instant_bridge_key"
-        perms = "0600"
-      }
-
-      template {
-        data = <<-EOH
           XDG_CONFIG_HOME="local/.config"
           INSTANT_BRIDGE_LOG_LEVEL="{{ job.env.get('log-level', 'info') }}"
           INSTANT_BRIDGE_LOG_FMT="{{ job.env.get('log-format', 'json') }}"
@@ -96,6 +84,14 @@ job "{{ job.name }}" {
           {{- range nomadService "{% endraw %}{{ job.target.name }}{% raw %}" }}
             {{- if contains "rpc" .Tags }}
           INSTANT_BRIDGE_BIDDER_RPC_URL="{{ .Address }}:{{ .Port }}"
+            {{- end }}
+          {{- end }}
+          CONTRACT_DEPLOYER_KEYSTORE_PATH="/local/data-{{ env "NOMAD_ALLOC_INDEX" }}/keystore"
+          CONTRACT_DEPLOYER_KEYSTORE_FILENAME="{{ with secret "secret/data/mev-commit" }}{{ .Data.data.contract_deployer_keystore_filename }}{{ end }}"
+          CONTRACT_DEPLOYER_KEYSTORE_PASSWORD="{{ with secret "secret/data/mev-commit" }}{{ .Data.data.contract_deployer_keystore_password }}{{ end }}"
+          {{- range nomadService "mock-l1" }}
+            {{- if contains "ws" .Tags }}
+          L1_RPC_URL="ws://{{ .Address}}:{{ .Port }}"
             {{- end }}
           {{- end }}
           {% endraw %}
@@ -117,6 +113,11 @@ job "{{ job.name }}" {
           exec > >(nc {{ .Address }} {{ .Port }}) 2>&1
             {{ end }}
           {{- end }}
+          mkdir -p "${CONTRACT_DEPLOYER_KEYSTORE_PATH}" > /dev/null 2>&1
+            {{- with secret "secret/data/mev-commit" }}
+          CONTRACT_DEPLOYER_KEYSTORE_FILE="${CONTRACT_DEPLOYER_KEYSTORE_PATH}/${CONTRACT_DEPLOYER_KEYSTORE_FILENAME}"
+          echo '{{ .Data.data.contract_deployer_keystore }}' > "${CONTRACT_DEPLOYER_KEYSTORE_FILE}"
+            {{ end }}
           {% endraw %}
 
           if [ ! -d ${INSTANT_BRIDGE_KEYSTORE_DIR} ]; then
@@ -137,6 +138,31 @@ job "{{ job.name }}" {
           export INSTANT_BRIDGE_SETTLEMENT_CONTRACT_ADDR="$(jq -r '.SettlementGateway' ${CONTRACTS_FILE})"
           export INSTANT_BRIDGE_L1_CONTRACT_ADDR="$(jq -r '.L1Gateway' ${CONTRACTS_FILE})"
             {{ end }}
+          {{- end }}
+          {% endraw %}
+
+          {%- raw %}
+          {{- range nomadService "mock-l1" }}
+            {{- if contains "ws" .Tags }}
+          L1_RPC_URL="ws://{{ .Address}}:{{ .Port }}"
+            {{- end }}
+            {{- with secret "secret/data/mev-commit" }}
+          ADDRESS="$(cat "${INSTANT_BRIDGE_KEYSTORE_DIR}/${INSTANT_BRIDGE_KEYSTORE_FILENAME}" | jq -r '.address')"
+            {{ end }}
+          cast send \
+            --keystore "${CONTRACT_DEPLOYER_KEYSTORE_FILE}" \
+            --password "${CONTRACT_DEPLOYER_KEYSTORE_PASSWORD}" \
+            --priority-gas-price 2000000000 \
+            --gas-price 5000000000 \
+            --value 100ether \
+            --rpc-url "${L1_RPC_URL}" \
+            "${ADDRESS}"
+
+          if [ $? -eq 0 ]; then
+            echo "Funds successfully sent to: ${ADDRESS}"
+          else
+            echo "Failed to send funds to: ${ADDRESS}"
+          fi
           {{- end }}
           {% endraw %}
 
