feat: restructure RPC service (#710)

diff --git a/infrastructure/nomad/playbooks/templates/jobs/preconf-rpc.nomad.j2 b/infrastructure/nomad/playbooks/templates/jobs/preconf-rpc.nomad.j2
--- a/infrastructure/nomad/playbooks/templates/jobs/preconf-rpc.nomad.j2
+++ b/infrastructure/nomad/playbooks/templates/jobs/preconf-rpc.nomad.j2
@@ -42,8 +42,118 @@ job "{{ job.name }}" {
       port = "{{ port_name }}"
       tags = ["{{ port_name }}"]
       provider = "nomad"
+      {% if port_name == "http" %}
+      check {
+        type     = "http"
+        path     = "/health"
+        interval = "10s"
+        timeout  = "2s"
+      }
+      {% endif %}
     }
     {% endfor %}
+
+    task "db" {
+      driver = "exec"
+
+      lifecycle {
+        hook    = "prestart"
+        sidecar = true
+      }
+
+      {% if profile == 'testnet' or profile == 'mainnet' %}
+      resources {
+        cores = 4
+        memory = 8192
+      }
+      {% elif profile == 'stressnet' or profile == 'stressnet-wl1' %}
+      resources {
+        memory = 4096
+      }
+      {% endif %}
+
+      template {
+        data = <<-EOH
+          POSTGRES_VERSION="15"
+          POSTGRES_DB="preconf-rpc"
+          POSTGRES_USERNAME="preconf-rpc"
+          POSTGRES_PASSWORD="{{ lookup('password', '/dev/null', length=64) }}"
+          {%- raw %}
+          POSTGRES_DATA="/local/pgdata-{{ env "NOMAD_ALLOC_INDEX" }}"
+          {{- range nomadService "{% endraw %}{{ job.name }}{% raw %}" }}
+            {{- if contains "db" .Tags }}
+          POSTGRES_PORT="{{ .Port }}"
+            {{- end }}
+          {{- end }}
+          {% endraw %}
+        EOH
+        destination = "alloc/data/postgres.env"
+        env = true
+      }
+
+      template {
+        data = <<-EOH
+          #!/usr/bin/env bash
+
+          {% raw %}
+          {{- range nomadService "datadog-agent-logs-collector" }}
+            {{ if contains "tcp" .Tags }}
+          exec > >(nc {{ .Address }} {{ .Port }}) 2>&1
+            {{ end }}
+          {{- end }}
+
+          if [ -d "${POSTGRES_DATA}" ]; then
+            echo "Initialized and configured database found."
+            cp "${POSTGRES_DATA}/.env" /alloc/data/postgres.env
+            source "${POSTGRES_DATA}/.env"
+            postgres -D ${POSTGRES_DATA}
+            exit $?
+          fi
+
+          export PATH="/usr/lib/postgresql/${POSTGRES_VERSION}/bin:${PATH}"
+          mkdir -p /var/run/postgresql > /dev/null 2>&1
+          pg_ctl initdb --silent --pgdata="${POSTGRES_DATA}"
+          if [ $? -ne 0 ]; then
+            echo "Failed to initialize PostgreSQL."
+            exit 1
+          fi
+          cp /alloc/data/postgres.env "${POSTGRES_DATA}/.env"
+
+          pg_ctl start --pgdata="${POSTGRES_DATA}" --silent --wait --timeout=300 > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "Failed to start PostgreSQL."
+            exit 1
+          fi
+
+          createuser --superuser postgres > /dev/null 2>&1
+          createuser --username=postgres --createdb "${POSTGRES_USERNAME}"
+          createdb --username="${POSTGRES_USERNAME}" "${POSTGRES_DB}"
+          psql --quiet \
+               --username="${POSTGRES_USERNAME}" \
+               --dbname="${POSTGRES_DB}" \
+               --command="ALTER USER ${POSTGRES_USERNAME} WITH PASSWORD '${POSTGRES_PASSWORD}'; \
+                          GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USERNAME};"
+          echo "Database initialized and configured successfully."
+
+          pg_ctl stop --pgdata="${POSTGRES_DATA}" --silent --wait --timeout=300 > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "Failed to stop PostgreSQL."
+            exit 1
+          fi
+
+          exec postgres -D "${POSTGRES_DATA}" -p "${POSTGRES_PORT}"
+          {% endraw %}
+        EOH
+        destination = "local/run.sh"
+        change_mode = "noop"
+        perms = "0755"
+      }
+
+      config {
+        command = "bash"
+        args = ["-c", "exec local/run.sh"]
+      }
+    }
 
     task "preconfrpc" {
       driver = "exec"
@@ -88,6 +198,12 @@ job "{{ job.name }}" {
           {{- range nomadService "{% endraw %}{{ job.target.name }}{% raw %}" }}
             {{- if contains "rpc" .Tags }}
           PRECONF_RPC_BIDDER_RPC_URL="{{ .Address }}:{{ .Port }}"
+            {{- end }}
+          {{- end }}
+          {{- range nomadService "{% endraw %}{{ job.name }}{% raw %}" }}
+            {{- if contains "db" .Tags }}
+          PRECONF_RPC_PG_HOST="localhost"
+          PRECONF_RPC_PG_PORT="{{ .Port }}"
             {{- end }}
           {{- end }}
           {% endraw %}
@@ -177,6 +293,19 @@ job "{{ job.name }}" {
             echo "Failed to send funds to: ${ADDRESS}"
           fi
           {{- end }}
+
+          source alloc/data/postgres.env
+          export PRECONF_RPC_PG_USER="${POSTGRES_USERNAME}"
+          export PRECONF_RPC_PG_PASSWORD="${POSTGRES_PASSWORD}"
+          export PRECONF_RPC_PG_DBNAME="${POSTGRES_DB}"
+
+          export PRECONF_RPC_DEPOSIT_ADDRESS="$(echo '{{ $secret.Data.data.deposit_keystore }}' | jq -r '.address')"
+          export PRECONF_RPC_BRIDGE_ADDRESS="$(echo '{{ $secret.Data.data.bridge_keystore }}' | jq -r '.address')"
+
+          if ! timeout 5m bash -c 'until pg_isready -h ${PRECONF_RPC_PG_HOST} -p ${PRECONF_RPC_PG_PORT} -U ${PRECONF_RPC_PG_USER} -d ${PRECONF_RPC_PG_DBNAME}; do sleep 2; done'; then
+            echo "Waiting for PostgreSQL to start..."
+            sleep 3
+          fi
           {% endraw %}
 
           chmod +x local/preconf-rpc
